export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  AGENT = 'AGENT',
  VIEWER = 'VIEWER',
}

export enum ConversationStatus {
  OPEN = 'OPEN',
  REQUESTED = 'REQUESTED',
  INTERVENED = 'INTERVENED',
  RESOLVED = 'RESOLVED',
  PENDING = 'PENDING',
  SNOOZED = 'SNOOZED',
}

export enum MessageStatus {
  QUEUED = 'QUEUED',
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  READ = 'READ',
  FAILED = 'FAILED',
}

export enum MessageType {
  TEXT = 'TEXT',
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
  AUDIO = 'AUDIO',
  DOCUMENT = 'DOCUMENT',
  TEMPLATE = 'TEMPLATE',
  INTERACTIVE = 'INTERACTIVE',
  LOCATION = 'LOCATION',
  CONTACTS = 'CONTACTS',
  STICKER = 'STICKER',
  NOTE = 'NOTE',
}

export enum MessageDirection {
  INBOUND = 'INBOUND',
  OUTBOUND = 'OUTBOUND',
}

export enum TemplateStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PAUSED = 'PAUSED',
}

export enum TemplateCategory {
  AUTHENTICATION = 'AUTHENTICATION',
  MARKETING = 'MARKETING',
  UTILITY = 'UTILITY',
}

export enum CampaignStatus {
  DRAFT = 'DRAFT',
  SCHEDULED = 'SCHEDULED',
  RUNNING = 'RUNNING',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum RecipientStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  READ = 'READ',
  FAILED = 'FAILED',
}

export enum AutomationTrigger {
  KEYWORD = 'KEYWORD',
  FIRST_MESSAGE = 'FIRST_MESSAGE',
  CONVERSATION_CREATED = 'CONVERSATION_CREATED',
  CONVERSATION_RESOLVED = 'CONVERSATION_RESOLVED',
  LABEL_ADDED = 'LABEL_ADDED',
  INACTIVITY = 'INACTIVITY',
}

export enum AutomationAction {
  SEND_MESSAGE = 'SEND_MESSAGE',
  SEND_TEMPLATE = 'SEND_TEMPLATE',
  ASSIGN_AGENT = 'ASSIGN_AGENT',
  UNASSIGN_AGENT = 'UNASSIGN_AGENT',
  ADD_LABEL = 'ADD_LABEL',
  REMOVE_LABEL = 'REMOVE_LABEL',
  ADD_NOTE = 'ADD_NOTE',
  RESOLVE_CONVERSATION = 'RESOLVE_CONVERSATION',
  SEND_WEBHOOK = 'SEND_WEBHOOK',
}

export enum MediaType {
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
  AUDIO = 'AUDIO',
  DOCUMENT = 'DOCUMENT',
}

export enum AuditAction {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  EXPORT = 'EXPORT',
  SEND_MESSAGE = 'SEND_MESSAGE',
  START_CAMPAIGN = 'START_CAMPAIGN',
}

export enum ChannelType {
  WHATSAPP = 'WHATSAPP',
  FACEBOOK_MESSENGER = 'FACEBOOK_MESSENGER',
  INSTAGRAM = 'INSTAGRAM',
  TELEGRAM = 'TELEGRAM',
  EMAIL = 'EMAIL',
  WEB_CHAT = 'WEB_CHAT',
  TIKTOK = 'TIKTOK',
  TWITTER = 'TWITTER',
  LINKEDIN = 'LINKEDIN',
}

export enum ActivityAction {
  CONVERSATION_CREATED = 'CONVERSATION_CREATED',
  CONVERSATION_ASSIGNED = 'CONVERSATION_ASSIGNED',
  CONVERSATION_UNASSIGNED = 'CONVERSATION_UNASSIGNED',
  CONVERSATION_REQUESTED = 'CONVERSATION_REQUESTED',
  CONVERSATION_INTERVENED = 'CONVERSATION_INTERVENED',
  CONVERSATION_RESOLVED = 'CONVERSATION_RESOLVED',
  CONVERSATION_REOPENED = 'CONVERSATION_REOPENED',
  CONVERSATION_ARCHIVED = 'CONVERSATION_ARCHIVED',
  CONVERSATION_TRANSFERRED = 'CONVERSATION_TRANSFERRED',
  MESSAGE_SENT = 'MESSAGE_SENT',
  MESSAGE_EDITED = 'MESSAGE_EDITED',
  MESSAGE_DELETED = 'MESSAGE_DELETED',
  MESSAGE_STARRED = 'MESSAGE_STARRED',
  NOTE_ADDED = 'NOTE_ADDED',
  NOTE_DELETED = 'NOTE_DELETED',
  TAG_ADDED = 'TAG_ADDED',
  TAG_REMOVED = 'TAG_REMOVED',
  CONTACT_UPDATED = 'CONTACT_UPDATED',
  CONTACT_BLOCKED = 'CONTACT_BLOCKED',
  AUTOMATION_TRIGGERED = 'AUTOMATION_TRIGGERED',
  CAMPAIGN_LAUNCHED = 'CAMPAIGN_LAUNCHED',
  SURVEY_RESPONSE = 'SURVEY_RESPONSE',
  CALL_ENDED = 'CALL_ENDED',
  CALL_INITIATED = 'CALL_INITIATED',
  CALL_MISSED = 'CALL_MISSED',
  CALL_DECLINED = 'CALL_DECLINED',
  CALL_CANCELED = 'CALL_CANCELED',
}

export enum CallDirection {
  INCOMING = 'INCOMING',
  OUTGOING = 'OUTGOING',
}

/**
 * Finite call state machine.
 *
 * Outgoing (agent → customer):
 *   INITIATED → RINGING → ONGOING → ENDED
 *                        → DECLINED   (customer pressed decline)
 *                        → UNANSWERED (timeout, no answer)
 *   INITIATED/RINGING → CANCELED (agent hung up before answer)
 *
 * Incoming (customer → agent):
 *   direction=INCOMING + RINGING → ONGOING → ENDED
 *                                → DECLINED (agent pressed decline)
 *                                → MISSED   (agent didn't answer / timed out)
 */
export enum CallStatus {
  SCHEDULED    = 'SCHEDULED',
  INITIATED    = 'INITIATED',
  RINGING      = 'RINGING',
  ONGOING      = 'ONGOING',
  MISSED       = 'MISSED',
  DECLINED     = 'DECLINED',
  CANCELED     = 'CANCELED',
  UNANSWERED   = 'UNANSWERED',
  BUSY         = 'BUSY',
  FAILED       = 'FAILED',
  ENDED        = 'ENDED',
  RECONNECTING = 'RECONNECTING',
  HOLD         = 'HOLD',
  VOICEMAIL    = 'VOICEMAIL',
}

export enum SubscriptionStatus {
  TRIAL         = 'TRIAL',
  ACTIVE        = 'ACTIVE',
  PAST_DUE      = 'PAST_DUE',
  SUSPENDED     = 'SUSPENDED',
  CANCELED      = 'CANCELED',
  EXPIRED       = 'EXPIRED',
}

export enum BillingCycle {
  MONTHLY = 'MONTHLY',
  YEARLY  = 'YEARLY',
}

export enum PaymentGateway {
  STRIPE       = 'STRIPE',
  PAYSTACK     = 'PAYSTACK',
}

export enum PaymentStatus {
  PENDING    = 'PENDING',
  SUCCEEDED  = 'SUCCEEDED',
  FAILED     = 'FAILED',
  REFUNDED   = 'REFUNDED',
  DISPUTED   = 'DISPUTED',
}

export enum InvoiceStatus {
  DRAFT          = 'DRAFT',
  OPEN           = 'OPEN',
  PAID           = 'PAID',
  VOID           = 'VOID',
  UNCOLLECTIBLE  = 'UNCOLLECTIBLE',
}
